name: pose_ranker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scikit-learn
  - xmltodict
  - psutil
  - seaborn
  - matplotlib
  - tqdm
  - pandas
  - xgboost
  - pip
  - pip:
      - optuna
